//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyCompany("Tripp\'n Technology, LLC.")]
[assembly: System.Reflection.AssemblyConfiguration("Debug")]
[assembly: System.Reflection.AssemblyCopyright("Copyright Tripp\'n Technology, LLC. 2018")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.2032")]
[assembly: System.Reflection.AssemblyInformationalVersion("18.04.14.20.32")]
[assembly: System.Reflection.AssemblyVersion("1.0.0.2032")]


