<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyTitle>Landscape Sprinkler Designer Settings</AssemblyTitle>
		<Configurations>Debug;Release;Debug (PALETTE_PROPERTIES)</Configurations>
       <TargetFramework>net10.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="tnt.reflection" Version="2.0.0" />
		<PackageReference Include="TNT.Utilities" Version="3.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\TNT.LSD.Inventory\TNT.LSD.Inventory.csproj" />
	</ItemGroup>

</Project>
