<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<AssemblyVersion>$(PackageVersion)</AssemblyVersion>
		<Authors>Tripp'n Technology, LLC.</Authors>
		<Company>$(Authors)</Company>
		<Copyright>Copyright 2024 $(Authors)</Copyright>
		<Description>Checker</Description>
		<FileVersion>$(PackageVersion)</FileVersion>
		<Title>Checker</Title>
		<Version>0.0.1</Version>

	</PropertyGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="mkdir $(SolutionDir)LandscapeSprinklerDesigner\bin\Debug\plugins&#xD;&#xA;copy $(TargetPath) $(SolutionDir)LandscapeSprinklerDesigner\bin\Debug\plugins" />
	</Target>

	<ItemGroup>
	  <None Remove="Images\eye.png" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="Images\eye.png" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Libraries\TNT.LSD.Components\TNT.LSD.Components.csproj" />
	</ItemGroup>

</Project>
