<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyTitle>Landscape Sprinkler Designer Checker Plugin</AssemblyTitle>
		<Configurations>Debug;Release;Debug (PALETTE_PROPERTIES)</Configurations>
		<TargetFramework>net9.0-windows</TargetFramework>
		<Version>0.0.1</Version>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Images\eye.png" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Images\eye.png" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Libraries\TNT.LSD.Components\TNT.LSD.Components.csproj" />
	</ItemGroup>

</Project>
