<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AssemblyTitle>Landscape Sprinkler Designer Parts Editor Plugin</AssemblyTitle>
		<Configurations>Debug;Release;Debug (PALETTE_PROPERTIES)</Configurations>
		<TargetFramework>net9.0-windows</TargetFramework>
	</PropertyGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="call $(SolutionDir)Plugins\CopyPlugin.bat TNT.LSD.PartsEditor.dll $(TargetDir) $(SolutionDir)LandscapeSprinklerDesigner\bin\$(ConfigurationName)\net9.0-windows\plugins" />
	</Target>

	<ItemGroup>
		<ProjectReference Include="..\..\Libraries\TNT.LSD.Components\TNT.LSD.Components.csproj" />
		<ProjectReference Include="..\..\Libraries\TNT.LSD.Inventory\TNT.LSD.Inventory.csproj" />
	</ItemGroup>

</Project>
