<?xml version="1.0" encoding="utf-8"?>
<Project>
	<PropertyGroup>
		<Authors>$(Company)</Authors>
		<Company>Tripp'n Technology, LLC.</Company>
		<Copyright>Copyright © 2026 $(Company)</Copyright>
		<GenerateDocumentationFile>False</GenerateDocumentationFile>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Product>$(AssemblyTitle)</Product>
		<TargetFramework>net9.0</TargetFramework>
		<Version>4.0.3</Version>
	</PropertyGroup>
</Project>
