<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyTitle>Landscape Sprinkler Designer Exporter Plugin</AssemblyTitle>
		<Configurations>Debug;Release;Debug (PALETTE_PROPERTIES)</Configurations>
		<TargetFramework>net9.0-windows</TargetFramework>
	</PropertyGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="call $(SolutionDir)Plugins\CopyPlugin.bat TNT.LSD.Export.dll $(TargetDir) $(SolutionDir)LandscapeSprinklerDesigner\bin\$(ConfigurationName)\net9.0-windows\plugins" />
	</Target>

	<ItemGroup>
		<None Remove="Images\jpg.png" />
		<None Remove="Images\png.png" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Images\jpg.png" />
		<EmbeddedResource Include="Images\png.png" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Libraries\TNT.LSD.Components\TNT.LSD.Components.csproj" />
		<ProjectReference Include="..\..\Libraries\TNT.LSD.Settings\TNT.LSD.Settings.csproj" />
	</ItemGroup>

</Project>
