<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyTitle>Landscape Sprinkler Designer Colorizer Plugin</AssemblyTitle>
		<Configurations>Debug;Release;Debug (PALETTE_PROPERTIES)</Configurations>
       <TargetFramework>net10.0-windows</TargetFramework>
	</PropertyGroup>

 <Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="call $(SolutionDir)Plugins\CopyPlugin.bat TNT.LSD.Colorizer.dll $(TargetDir) $(SolutionDir)LandscapeSprinklerDesigner\bin\$(ConfigurationName)\net10.0-windows\plugins" />
	</Target>

	<ItemGroup>
		<None Remove="Images\paintbrush.png" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Images\paintbrush.png" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Libraries\TNT.LSD.Components\TNT.LSD.Components.csproj" />
		<ProjectReference Include="..\..\Libraries\TNT.LSD.Objects\TNT.LSD.Objects.csproj" />
	</ItemGroup>

</Project>
