<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<TargetFramework>net8.0-windows</TargetFramework>

		<Authors>Tripp'n Technology, LLC.</Authors>
		<Company>$(Authors)</Company>
		<Copyright>Copyright 2024 $(Authors)</Copyright>
		<FileVersion>$(PackageVersion)</FileVersion>
		<GenerateDocumentationFile>False</GenerateDocumentationFile>
		<Version>2.0.0</Version>
		<AssemblyTitle>Valve Colorizer</AssemblyTitle>
		<!-- File Description -->
		<Product>$(AssemblyTitle)</Product>
		<!-- Product Name -->

	</PropertyGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="mkdir $(SolutionDir)LandscapeSprinklerDesigner\bin\Debug\plugins&#xD;&#xA;copy $(TargetPath) $(SolutionDir)LandscapeSprinklerDesigner\bin\Debug\plugins" />
	</Target>

	<ItemGroup>
		<None Remove="Images\paintbrush.png" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Images\paintbrush.png" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Libraries\TNT.LSD.Components\TNT.LSD.Components.csproj" />
	</ItemGroup>

</Project>
