<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<!-- File Description -->
		<AssemblyTitle>Landscape Sprinkler Designer Components</AssemblyTitle>
		<Authors>Tripp'n Technology, LLC.</Authors>
		<Company>$(Authors)</Company>
		<Configurations>Debug;Release;Debug (PALETTE_PROPERTIES)</Configurations>
		<Copyright>Copyright 2024 $(Authors)</Copyright>
		<FileVersion>$(PackageVersion)</FileVersion>
		<GenerateDocumentationFile>False</GenerateDocumentationFile>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<!-- Product Name -->
		<Product>$(AssemblyTitle)</Product>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Version>2.0.0</Version>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="TNTCADTest\**" />
		<EmbeddedResource Remove="TNTCADTest\**" />
		<None Remove="TNTCADTest\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="DockPanelSuite" Version="3.1.0" />
		<PackageReference Include="DotNetZip" Version="1.16.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.1" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
		<PackageReference Include="TNT.Commons" Version="1.0.1" />
		<PackageReference Include="TNT.Math" Version="2.0.0" />
		<PackageReference Include="TNT.Plugin.Manager" Version="2.0.0" />
		<PackageReference Include="TNT.Utilities" Version="2.1.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\TNT.LSD.Inventory\TNT.LSD.Inventory.csproj">
			<PrivateAssets>all</PrivateAssets>
			<ExcludeAssets>all</ExcludeAssets>
		</ProjectReference>
		<ProjectReference Include="..\TNT.LSD.Objects\TNT.LSD.Objects.csproj">
			<PrivateAssets>all</PrivateAssets>
			<ExcludeAssets>all</ExcludeAssets>
		</ProjectReference>
		<ProjectReference Include="..\TNT.LSD.Settings\TNT.LSD.Settings.csproj">
			<PrivateAssets>all</PrivateAssets>
			<ExcludeAssets>all</ExcludeAssets>
		</ProjectReference>


	</ItemGroup>

</Project>
