<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AssemblyTitle>Landscape Sprinkler Designer SSC Plugin</AssemblyTitle>
		<Configurations>Debug;Release;Debug (PALETTE_PROPERTIES)</Configurations>
		<TargetFramework>net10.0-windows</TargetFramework>
	</PropertyGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="call $(SolutionDir)Plugins\CopyPlugin.bat TNT.LSD.SSC.dll $(TargetDir) $(SolutionDir)LandscapeSprinklerDesigner\bin\$(ConfigurationName)\net10.0-windows\plugins" />
	</Target>

	<ItemGroup>
		<None Remove="Images\email_attach.png" />
		<None Remove="Images\package.png" />
		<None Remove="Images\pdf-ssc-icon.png" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Images\email_attach.png" />
		<EmbeddedResource Include="Images\package.png" />
		<EmbeddedResource Include="Images\pdf-ssc-icon.png" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3912.50" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Libraries\TNT.LSD.Components\TNT.LSD.Components.csproj" />
		<ProjectReference Include="..\..\Libraries\TNT.LSD.Objects\TNT.LSD.Objects.csproj" />
		<ProjectReference Include="..\..\Libraries\TNT.LSD.PDFGenerator\TNT.LSD.PDFGenerator.csproj" />
	</ItemGroup>

</Project>