<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<TargetFramework>net8.0-windows</TargetFramework>

		<!-- File Description -->
		<AssemblyTitle>Landscape Sprinkler Designer SSC Plugin</AssemblyTitle>
		<Authors>Tripp'n Technology, LLC.</Authors>
		<Company>$(Authors)</Company>
		<Copyright>Copyright 2024 $(Authors)</Copyright>
		<FileVersion>$(PackageVersion)</FileVersion>
		<GenerateDocumentationFile>False</GenerateDocumentationFile>
		<!-- Product Name -->
		<Product>$(AssemblyTitle)</Product>
		<Version>2.0.0</Version>

	</PropertyGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="mkdir $(SolutionDir)LandscapeSprinklerDesigner\bin\Debug\plugins&#xD;&#xA;copy $(TargetPath) $(SolutionDir)LandscapeSprinklerDesigner\bin\Debug\plugins" />
	</Target>

	<ItemGroup>
	  <None Remove="Images\email_attach.png" />
	  <None Remove="Images\package.png" />
	  <None Remove="Images\pdf-ssc-icon.png" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="Images\email_attach.png" />
	  <EmbeddedResource Include="Images\package.png" />
	  <EmbeddedResource Include="Images\pdf-ssc-icon.png" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Libraries\TNT.LSD.Components\TNT.LSD.Components.csproj" />
	  <ProjectReference Include="..\..\Libraries\TNT.LSD.PDFGenerator\TNT.LSD.PDFGenerator.csproj" />
	</ItemGroup>
	
</Project>