//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyCompany("Tripp\'n Technology, LLC.")]
[assembly: System.Reflection.AssemblyConfiguration("Debug")]
[assembly: System.Reflection.AssemblyCopyright("Copyright 2020 Tripp\'n Technology, LLC.")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.1.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.0.1.0-2005302107")]
[assembly: System.Reflection.AssemblyTitle("Background Importer")]
[assembly: System.Reflection.AssemblyVersion("1.0.1.0")]
[assembly: System.Reflection.AssemblyDescription("Background Importer")]
[assembly: System.Reflection.AssemblyProduct("Background Importer")]


