//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyCompany("Tripp\'n Technology, LLC.")]
[assembly: System.Reflection.AssemblyConfiguration("Debug")]
[assembly: System.Reflection.AssemblyCopyright("Copyright 2019 Tripp\'n Technology, LLC.")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.0.0.0-1910022109")]
[assembly: System.Reflection.AssemblyTitle("Landscape Sprinkler Designer Components")]
[assembly: System.Reflection.AssemblyVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyDescription("Landscape Sprinkler Designer Components")]
[assembly: System.Reflection.AssemblyProduct("Landscape Sprinkler Designer Components")]
[assembly: System.Runtime.InteropServices.Guid("34a0198b-a28b-4161-9af7-b9ba2256e0a8")]


