<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<!-- File Description -->
		<ApplicationIcon>LandscapeSprinklerDesigner.ico</ApplicationIcon>
		<AssemblyTitle>Landscape Sprinkler Designer</AssemblyTitle>
		<Authors>Tripp'n Technology, LLC.</Authors>
		<Company>$(Authors)</Company>
		<Copyright>Copyright 2025 $(Authors)</Copyright>
		<Description>$(AssemblyTitle)</Description>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<OutputType>WinExe</OutputType>
		<!-- Product Name -->
		<Product>$(AssemblyTitle)</Product>
		<TargetFramework>net9.0-windows</TargetFramework>
		<Title>$(AssemblyTitle)</Title>
		<UseWindowsForms>true</UseWindowsForms>
		<Version>4.0.3</Version>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'" />

	<ItemGroup>
		<PackageReference Include="DockPanelSuite" Version="3.1.1" />
		<PackageReference Include="DockPanelSuite.ThemeVS2015" Version="3.1.1" />
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3719.77" />
		<PackageReference Include="TNT.Commons" Version="2.0.2" />
		<PackageReference Include="TNT.Cryptography" Version="3.0.4" />
		<PackageReference Include="TNT.Reactive" Version="1.1.0" />
		<PackageReference Include="TNT.Services.Client" Version="1.0.3" />
		<PackageReference Include="TNT.ToolStripItemManager" Version="4.0.5" />
		<PackageReference Include="TNT.Utilities" Version="3.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Libraries\TNT.LSD.Components\TNT.LSD.Components.csproj" />
		<ProjectReference Include="..\Libraries\TNT.LSD.Objects\TNT.LSD.Objects.csproj" />
		<ProjectReference Include="..\Libraries\TNT.LSD.PDFGenerator\TNT.LSD.PDFGenerator.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Resource.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resource.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Resource.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Resource.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<None Update="appsettings.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="palette.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="copy &quot;$(SolutionDir)Database\Inventory.sqlite&quot; &quot;$(TargetDir)&quot;" />
		<!--<Exec Command="mkdir &quot;$(TargetDir)plugins&quot;" />-->
		<!--<Exec Command="xcopy &quot;$(SolutionDir)Plugins\TNT.LSD.Background\bin\Debug\net9.0-windows\TNT.LSD.Background.dll&quot; &quot;$(TargetDir)plugins\TNT.LSD.Background.dll&quot;" />
		<Exec Command="xcopy &quot;$(SolutionDir)Plugins\TNT.LSD.Colorizer\bin\Debug\net9.0-windows\TNT.LSD.Colorizer.dll&quot; &quot;$(TargetDir)plugins\TNT.LSD.Colorizer.dll&quot;" />-->
	</Target>

</Project>