//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyCompany("Tripp\'n Technology, LLC.")]
[assembly: System.Reflection.AssemblyConfiguration("Debug")]
[assembly: System.Reflection.AssemblyCopyright("Copyright Tripp\'n Technology, LLC. 2019")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.0.0.0-1904161742")]
[assembly: System.Reflection.AssemblyTitle("Landscape Sprinkler Designer Inventory")]
[assembly: System.Reflection.AssemblyVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyDescription("Landscape Sprinkler Designer Inventory")]
[assembly: System.Reflection.AssemblyProduct("Landscape Sprinkler Designer Inventory")]
[assembly: System.Runtime.InteropServices.Guid("8f3113a7-e598-4c9a-8427-7e3c6d33c0cb")]


