//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyCompany("Tripp\'n Technology, LLC.")]
[assembly: System.Reflection.AssemblyConfiguration("Debug")]
[assembly: System.Reflection.AssemblyCopyright("Copyright Tripp\'n Technology, LLC. 2019")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.0.0.0-1902091020")]
[assembly: System.Reflection.AssemblyTitle("Palette Designer")]
[assembly: System.Reflection.AssemblyVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyDescription("Palette Designer")]
[assembly: System.Reflection.AssemblyProduct("Palette Designer")]
[assembly: System.Runtime.InteropServices.Guid("80608b77-d677-4999-b0ce-adf6e9fd5e59")]


