<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyTitle>Landscape Sprinkler Designer Background Plugin</AssemblyTitle>
		<Configurations>Debug;Release;Debug (PALETTE_PROPERTIES)</Configurations>
       <TargetFramework>net10.0-windows</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Images\import_background_image.png" />
		<None Remove="Images\show_landscape.png" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Images\import_background_image.png" />
		<EmbeddedResource Include="Images\show_landscape.png" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="TNT.Plugin.Manager" Version="2.0.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Libraries\TNT.LSD.Components\TNT.LSD.Components.csproj" />
	</ItemGroup>

 <Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="call $(SolutionDir)Plugins\CopyPlugin.bat TNT.LSD.Background.dll $(TargetDir) $(SolutionDir)LandscapeSprinklerDesigner\bin\$(ConfigurationName)\net10.0-windows\plugins" />
	</Target>

</Project>
