//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandscapeSprinklerDesigner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LandscapeSprinklerDesigner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Clone.
        /// </summary>
        internal static string menu_clone {
            get {
                return ResourceManager.GetString("menu_clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a clone of the selected object(s).
        /// </summary>
        internal static string menu_clone_tooltip {
            get {
                return ResourceManager.GetString("menu_clone_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete.
        /// </summary>
        internal static string menu_delete {
            get {
                return ResourceManager.GetString("menu_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected object(s).
        /// </summary>
        internal static string menu_delete_tooltip {
            get {
                return ResourceManager.GetString("menu_delete_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string menu_exit {
            get {
                return ResourceManager.GetString("menu_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit the application.
        /// </summary>
        internal static string menu_exit_tooltip {
            get {
                return ResourceManager.GetString("menu_exit_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New.
        /// </summary>
        internal static string menu_new {
            get {
                return ResourceManager.GetString("menu_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new layout.
        /// </summary>
        internal static string menu_new_tooltip {
            get {
                return ResourceManager.GetString("menu_new_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open.
        /// </summary>
        internal static string menu_open {
            get {
                return ResourceManager.GetString("menu_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open layout.
        /// </summary>
        internal static string menu_open_tooltip {
            get {
                return ResourceManager.GetString("menu_open_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Properties Editor.
        /// </summary>
        internal static string menu_properties {
            get {
                return ResourceManager.GetString("menu_properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide/Show properties editor.
        /// </summary>
        internal static string menu_properties_tooltip {
            get {
                return ResourceManager.GetString("menu_properties_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        internal static string menu_save {
            get {
                return ResourceManager.GetString("menu_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp;As.
        /// </summary>
        internal static string menu_save_as {
            get {
                return ResourceManager.GetString("menu_save_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save layout with new name.
        /// </summary>
        internal static string menu_save_as_tooltip {
            get {
                return ResourceManager.GetString("menu_save_as_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save layout.
        /// </summary>
        internal static string menu_save_tooltip {
            get {
                return ResourceManager.GetString("menu_save_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &amp;All.
        /// </summary>
        internal static string menu_select_all {
            get {
                return ResourceManager.GetString("menu_select_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all objects.
        /// </summary>
        internal static string menu_select_all_tooltip {
            get {
                return ResourceManager.GetString("menu_select_all_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Grid.
        /// </summary>
        internal static string menu_show_grid {
            get {
                return ResourceManager.GetString("menu_show_grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle grid visibility.
        /// </summary>
        internal static string menu_show_grip_tooltip {
            get {
                return ResourceManager.GetString("menu_show_grip_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Undo.
        /// </summary>
        internal static string menu_undo {
            get {
                return ResourceManager.GetString("menu_undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo previous action.
        /// </summary>
        internal static string menu_undo_tooltip {
            get {
                return ResourceManager.GetString("menu_undo_tooltip", resourceCulture);
            }
        }
    }
}
