//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandscapeSprinklerDesigner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LandscapeSprinklerDesigner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LandscapeSprinklerDesigner.
        /// </summary>
        internal static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tripp&apos;n Technology.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align To Grid.
        /// </summary>
        internal static string menu_align_to_grid {
            get {
                return ResourceManager.GetString("menu_align_to_grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aligns selected objects to nearest grid intersection.
        /// </summary>
        internal static string menu_align_to_grid_tooltip {
            get {
                return ResourceManager.GetString("menu_align_to_grid_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Size Pipe.
        /// </summary>
        internal static string menu_auto_size {
            get {
                return ResourceManager.GetString("menu_auto_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size the pipe allow for required flow rates.
        /// </summary>
        internal static string menu_auto_size_tooltip {
            get {
                return ResourceManager.GetString("menu_auto_size_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate Area.
        /// </summary>
        internal static string menu_calculate_area {
            get {
                return ResourceManager.GetString("menu_calculate_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets the area of the selected enclosed object(s).
        /// </summary>
        internal static string menu_calculate_area_tooltip {
            get {
                return ResourceManager.GetString("menu_calculate_area_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate Length.
        /// </summary>
        internal static string menu_calculate_length {
            get {
                return ResourceManager.GetString("menu_calculate_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets the length of the selected object(s).
        /// </summary>
        internal static string menu_calculate_length_tooltip {
            get {
                return ResourceManager.GetString("menu_calculate_length_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check For Update.
        /// </summary>
        internal static string menu_check_for_update {
            get {
                return ResourceManager.GetString("menu_check_for_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks if there is an update availble.
        /// </summary>
        internal static string menu_check_for_update_tooltip {
            get {
                return ResourceManager.GetString("menu_check_for_update_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Clone.
        /// </summary>
        internal static string menu_clone {
            get {
                return ResourceManager.GetString("menu_clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a clone of the selected object(s).
        /// </summary>
        internal static string menu_clone_tooltip {
            get {
                return ResourceManager.GetString("menu_clone_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete.
        /// </summary>
        internal static string menu_delete {
            get {
                return ResourceManager.GetString("menu_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected object(s).
        /// </summary>
        internal static string menu_delete_tooltip {
            get {
                return ResourceManager.GetString("menu_delete_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string menu_exit {
            get {
                return ResourceManager.GetString("menu_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit the application.
        /// </summary>
        internal static string menu_exit_tooltip {
            get {
                return ResourceManager.GetString("menu_exit_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Label Heads.
        /// </summary>
        internal static string menu_label_heads {
            get {
                return ResourceManager.GetString("menu_label_heads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labels the heads with their coverage.
        /// </summary>
        internal static string menu_label_heads_tooltip {
            get {
                return ResourceManager.GetString("menu_label_heads_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout Settings.
        /// </summary>
        internal static string menu_layout_settings {
            get {
                return ResourceManager.GetString("menu_layout_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide/Show layout settings.
        /// </summary>
        internal static string menu_layout_settings_tooltip {
            get {
                return ResourceManager.GetString("menu_layout_settings_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move To Back.
        /// </summary>
        internal static string menu_move_to_back {
            get {
                return ResourceManager.GetString("menu_move_to_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring selected object(s) to the back.
        /// </summary>
        internal static string menu_move_to_back_tooltip {
            get {
                return ResourceManager.GetString("menu_move_to_back_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring To Front.
        /// </summary>
        internal static string menu_move_to_front {
            get {
                return ResourceManager.GetString("menu_move_to_front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring selected object(s) to the front.
        /// </summary>
        internal static string menu_move_to_front_tooltip {
            get {
                return ResourceManager.GetString("menu_move_to_front_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New.
        /// </summary>
        internal static string menu_new {
            get {
                return ResourceManager.GetString("menu_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new layout.
        /// </summary>
        internal static string menu_new_tooltip {
            get {
                return ResourceManager.GetString("menu_new_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open.
        /// </summary>
        internal static string menu_open {
            get {
                return ResourceManager.GetString("menu_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open layout.
        /// </summary>
        internal static string menu_open_tooltip {
            get {
                return ResourceManager.GetString("menu_open_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts Listing.
        /// </summary>
        internal static string menu_parts_listing {
            get {
                return ResourceManager.GetString("menu_parts_listing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide/Show parts listing.
        /// </summary>
        internal static string menu_parts_listing_tooltip {
            get {
                return ResourceManager.GetString("menu_parts_listing_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts Palette.
        /// </summary>
        internal static string menu_parts_palette {
            get {
                return ResourceManager.GetString("menu_parts_palette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide/Show parts palette.
        /// </summary>
        internal static string menu_parts_palette_tooltip {
            get {
                return ResourceManager.GetString("menu_parts_palette_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties Editor.
        /// </summary>
        internal static string menu_properties {
            get {
                return ResourceManager.GetString("menu_properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide/Show properties editor.
        /// </summary>
        internal static string menu_properties_tooltip {
            get {
                return ResourceManager.GetString("menu_properties_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string menu_register {
            get {
                return ResourceManager.GetString("menu_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register the application.
        /// </summary>
        internal static string menu_register_tooltip {
            get {
                return ResourceManager.GetString("menu_register_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate 180.
        /// </summary>
        internal static string menu_rotate_180 {
            get {
                return ResourceManager.GetString("menu_rotate_180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotates the selected image(s) 180 degrees.
        /// </summary>
        internal static string menu_rotate_180_tooltip {
            get {
                return ResourceManager.GetString("menu_rotate_180_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate 90 Counterclockwise.
        /// </summary>
        internal static string menu_rotate_left {
            get {
                return ResourceManager.GetString("menu_rotate_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotates the selected image(s) 90 degrees counterclockwise.
        /// </summary>
        internal static string menu_rotate_left_tooltip {
            get {
                return ResourceManager.GetString("menu_rotate_left_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate 90 Clockwise.
        /// </summary>
        internal static string menu_rotate_right {
            get {
                return ResourceManager.GetString("menu_rotate_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotates the selected image(s) 90 degrees clockwise.
        /// </summary>
        internal static string menu_rotate_right_tooltip {
            get {
                return ResourceManager.GetString("menu_rotate_right_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        internal static string menu_save {
            get {
                return ResourceManager.GetString("menu_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp;As.
        /// </summary>
        internal static string menu_save_as {
            get {
                return ResourceManager.GetString("menu_save_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save layout with new name.
        /// </summary>
        internal static string menu_save_as_tooltip {
            get {
                return ResourceManager.GetString("menu_save_as_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save layout.
        /// </summary>
        internal static string menu_save_tooltip {
            get {
                return ResourceManager.GetString("menu_save_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &amp;All.
        /// </summary>
        internal static string menu_select_all {
            get {
                return ResourceManager.GetString("menu_select_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all objects.
        /// </summary>
        internal static string menu_select_all_tooltip {
            get {
                return ResourceManager.GetString("menu_select_all_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Coverage.
        /// </summary>
        internal static string menu_show_coverage {
            get {
                return ResourceManager.GetString("menu_show_coverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the sprinkler coverage.
        /// </summary>
        internal static string menu_show_coverage_tooltip {
            get {
                return ResourceManager.GetString("menu_show_coverage_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows measurements even when the object isn&apos;t selected.
        /// </summary>
        internal static string menu_show_distance_tooltip {
            get {
                return ResourceManager.GetString("menu_show_distance_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always Show &amp;Distances.
        /// </summary>
        internal static string menu_show_distances {
            get {
                return ResourceManager.GetString("menu_show_distances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Grid.
        /// </summary>
        internal static string menu_show_grid {
            get {
                return ResourceManager.GetString("menu_show_grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle grid visibility.
        /// </summary>
        internal static string menu_show_grip_tooltip {
            get {
                return ResourceManager.GetString("menu_show_grip_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape Image.
        /// </summary>
        internal static string menu_show_landscape_image {
            get {
                return ResourceManager.GetString("menu_show_landscape_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide/Show Landscape Image.
        /// </summary>
        internal static string menu_show_landscape_image_tooltip {
            get {
                return ResourceManager.GetString("menu_show_landscape_image_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part &amp;Tooltip.
        /// </summary>
        internal static string menu_show_parts {
            get {
                return ResourceManager.GetString("menu_show_parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the parts that represent the image.
        /// </summary>
        internal static string menu_show_parts_tooltip {
            get {
                return ResourceManager.GetString("menu_show_parts_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap To Grid.
        /// </summary>
        internal static string menu_snap_to_grid {
            get {
                return ResourceManager.GetString("menu_snap_to_grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable/Disable snap-to-grid.
        /// </summary>
        internal static string menu_snap_to_grid_tooltip {
            get {
                return ResourceManager.GetString("menu_snap_to_grid_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space Equally.
        /// </summary>
        internal static string menu_space_equally {
            get {
                return ResourceManager.GetString("menu_space_equally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spaces selected object equally.
        /// </summary>
        internal static string menu_space_equally_tooltip {
            get {
                return ResourceManager.GetString("menu_space_equally_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum GPM.
        /// </summary>
        internal static string menu_sum_gpm {
            get {
                return ResourceManager.GetString("menu_sum_gpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum GPM of selected lateral parts.
        /// </summary>
        internal static string menu_sum_gpm_tooltip {
            get {
                return ResourceManager.GetString("menu_sum_gpm_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Undo.
        /// </summary>
        internal static string menu_undo {
            get {
                return ResourceManager.GetString("menu_undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo previous action.
        /// </summary>
        internal static string menu_undo_tooltip {
            get {
                return ResourceManager.GetString("menu_undo_tooltip", resourceCulture);
            }
        }
    }
}
